[package]
name = "movement"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
fmc_client_api = "0.0.5"

bincode = "1.3.3"
serde = { version = "1.0.188", features = ["derive"] }

